---
ID: "9737d930-0760-42d5-9313-fd212e30d3f8"
Parent: "df57d580-aa87-4553-9e15-b7b5319c4c1f"
Template: "df57d580-aa87-4553-9e15-b7b5319c4c1f"
Path: "/sitecore/templates/Project/industry-verticals/Rendering Parameters/HeroPromo Parameters/__Standard Values"
Languages:
- Language: en
  Versions:
  - Version: 1
    Fields:
    - ID: "25bed78c-4957-4165-998a-ca1b52f67497"
      Hint: __Created
      Value: 20211012T120926Z
    - ID: "5dd74568-4d4b-44c1-b513-0af5f4cda34f"
      Hint: __Created by
      Value: |
        sitecore\JssImport
    - ID: "8cdc337e-a112-42fb-bbb4-4143751e123f"
      Hint: __Revision
      Value: "4ceed529-6184-494c-8fd1-ae7db56faa5f"
    - ID: "badd9cf9-53e0-4d0c-bcc0-2d784c282f6a"
      Hint: __Updated by
      Value: |
        sitecore\rob.horton@sitecore.com
    - ID: "d9cf14b1-fa16-4ba6-9288-e8a174d4d522"
      Hint: __Updated
      Value: 20260518T032407Z
