/**
 * Ambient modules for files generated by `sitecore-tools project build`.
 * They are gitignored until a build runs with Edge/local API configured.
 * Declarations allow `tsc --noEmit` (e.g. pre-commit) to pass; real JSON is produced at build time.
 */
declare module '.sitecore/sites.json' {
  import type { SiteInfo } from '@sitecore-content-sdk/nextjs';
  const sites: SiteInfo[];
  export default sites;
}

declare module '.sitecore/metadata.json' {
  import type { Metadata } from '@sitecore-content-sdk/nextjs/editing';
  const metadata: Metadata;
  export default metadata;
}
